transmission:
  username: YOUR_TRANSMISSION_USERNAME
  password: YOUR_TRANSMISSION_PASSWORD
  host: 127.0.0.1
  port: 9091

tautulli:
  apikey: YOUR_TAUTULLI_API_KEY
  baseurl: http://localhost:8181/api/v2

throttling:
  stream_count: 2

webhooks: []

speed: # KB/s
  normal:
    download: 5000
    upload: 500
  throttled:
    download: 5000
    upload: 2500